# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=600)),
                ('orig_title', models.TextField(default='', max_length=800, null=True)),
                ('magnet', models.TextField(max_length=1200)),
                ('provider_url', models.TextField(max_length=600)),
                ('provider', models.CharField(db_index=True, default='Extratorrent.cc', editable=False, max_length=200)),
                ('t_hash', models.CharField(max_length=40, null=True)),
                ('file_list', models.TextField(null=True)),
                ('peers', models.IntegerField(db_index=True, null=True)),
                ('seeds', models.IntegerField(db_index=True, null=True)),
                ('complete', models.IntegerField(null=True)),
                ('tr_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('last_check', models.DateTimeField(db_index=True, null=True)),
                ('count_check', models.IntegerField(db_index=True, null=True)),
                ('priority', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='torrent',
            unique_together=set([('magnet', 'provider_url')]),
        ),
    ]
