# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 00:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_torrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='name_pars',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='tr_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, null=True),
        ),
    ]
