# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_torrent', '0002_auto_20161226_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='last_check',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
